---
title: Visualization extension
format:
  html:
    toc: true
    number-sections: true
engine: julia
execute:
  freeze: auto
  cache: true
---

```{julia}
#| echo: false
#| output: false
using StructuralVibration, ShareAdd
@usingany CairoMakie
```

`StructuralVibration.jl` is accompanied by two extensions `CairoMakieExt.jl` and `GLMakieExt.jl` providing visualization capabilities. The extensions provide a set of functions to visualize the results of the structural dynamics analysis.

To use one of these extensions, you need to import the desired plotting package by running the following command:
```julia
using CairoMakie

# or

using GLMakie
```

## Bode plot

A Bode plot is a graph of the magnitude and phase of a transfer function versus frequency.

::: {.api}
**bode_plot**

---
```{julia}
#| echo: false
@doc bode_plot
```
:::

```{julia}
# Initialize a Sdof type
m = 1.
f₀ = 10.
ξ = 0.01
sdof = Sdof(m, f₀, ξ)

# Computation parameters
freq = 1.:0.01:30.

# Compute the FRF
prob_frf = SdofFRFProblem(sdof, freq)
H = solve(prob_frf).u

# Bode plot
bode_plot(freq, H)
```

## Nyquist plot

The Nyquist plot is either a 2D or 3D plot. In 2D, it is a graph of the imaginary part versus the real part of the transfer function. In 3D, it is a graph of the imaginary part versus the real part of the transfer function and the frequency.

### 2D plot

::: {.api}
**nyquist_plot**

---
```{julia}
#| echo: false
@doc nyquist_plot(y::Vector{ComplexF64}, theme = :makie; fonts = DEFAULT_MAKIE_FONTS)
```
:::

```{julia}
nyquist_plot(H)
```

### 3D plot

::: {.api}
**nyquist_plot**

---
```{julia}
#| echo: false
@doc nyquist_plot(freq, y::Vector{ComplexF64}, ylabel = "Frequency (Hz)", theme = :makie; projection = false, fonts = DEFAULT_MAKIE_FONTS)
```
:::

```{julia}
nyquist_plot(freq, H, projection = true)
```