---
title: Primer on EMA
format:
  html:
    toc: true
    number-sections: true
engine: julia
execute:
  freeze: auto
  cache: true
---

The modal approach enables the dynamic behavior of a structure to be predicted based on knowledge of its natural modes of vibration, which are intrinsic to the system. From a practical point of view, this information can be used to determine the frequencies at which the structure is most likely to vibrate. For industry, this information is invaluable, as vibrations can cause discomfort, noise, premature wear and tear, or even damage to a system. This is where **Experimental Modal Analysis** (EMA) comes in. Experimental identification of vibration modes can also be used to calibrate a finite element model or certify a product (e.g. ground vibration testing or regulations related to the modal behavior of the structure).

EMA aims to estimate the natural frequencies of the system and other characteristic parameters (e.g. damping ratios and mode shapes) from the vibration measurements in order to obtain a modal model of the system under consideration. This model can then be used to determine the structure's dynamic behaviour for a given excitation.

To reach these goals, it is supposed that:

* the system is **linear and time-invariant** ;
* the modal damping is of **viscous** type.

EMA is a family of **inverse methods** attempting to determine the modal characteristics of a structure from the responses measured at each point of the mesh.

## General principles

To identify the modal parameters of a structure or mechanical system, EMA relies on the measurement of the structure's transfer function matrix. By definition, the transfer function $H_{pq}(\omega)$ can be seen as the frequency response of the system at a point $x_p$ to an excitation of unit amplitude at a point $x_q$. Classically, the transfer function matrix (here the admittance) is given by the relation

$$
H_{pq}(\omega) = \sum_{i = 1}^{+\infty} \frac{\phi_i(x_p)\, \phi_i(x_q)}{M_i(\omega_i^2 - \omega^2 + 2j\xi_i\omega_i\omega)} = \sum_{i = 1}^{+\infty} \left[\frac{{}_i R_{pq}}{(j\omega - \lambda_i)} + \frac{{}_i R_{pq}^\ast}{(j\omega - \lambda_i^\ast)}\right],
$$
where:

* $\lambda_i = -\xi_i + j\,\Omega_i$ is the pole related to the mode $i$, with:
    * $\Omega_i = \omega_i\sqrt{1 - \xi_i^2}$ is the damped natural frequency of the mode $i$, with $\omega_i = \vert \lambda_i\vert$.
    * $\xi_i = -\frac{\text{Re}(\lambda_i)}{\omega_i}$ the modal damping factor of the mode $i$ <br></br>

* ${}_i R_{pq} = c_i\, \phi_i(x_p)\, \phi_i(x_q)$ is the residue of the mode $i$, with:
    * $\phi_i(x_p)$ the mode shape of the mode $i$ at point $x_p$
    * $c_i = \frac{1}{2jM_i\Omega_i}$ the normalization constant of the mode shape of the mode $i$

The objective of an EMA is therefore to identify the residuals ${}_i R_{pq}$ and the poles $\lambda_i$ of the transfer function $H_{pq}(\omega)$ in order to extract, in a second step, the modal parameters of the system under study (natural angular frequencies $\omega_i$, modal damping factors $\xi_i$ and mode shapes $\phi_i$).

## Modal parameters extraction methods

In this `StructuralVibration.jl`, two families of modal extraction methods are implemented:

* methods based on the use of single degree of freedom (sdof) models, known as **Sdof methods**. These methods seek to adjust ideal transfer functions of Sdof systems to experimental curves around their resonances. These methods therefore consist of identifying the modal parameters mode by mode. To do this, the operator must select a frequency band around each resonance to perform the extraction. Currently, three Sdof methods are implemented in this package:

    * Peak Picking method
    * Circle Fit method
    * Least Squares Fit method

* methods based on the use of multiple degree of freedom (mdof) models, known as **Mdof methods**. These methods consider that the system can be represented as a multiple degree of freedom system. They are generally based on the construction of a high-order polynomial matrix whose coefficients are estimated from the measured transfer functions.Three Mdof methods are implemented in this package:

    * Least-Squares Complex Exponential method
    * Least-Squares Complex Frequency-domain method
    * Polyreference Least-Squares Complex Frequency-domain method

